-- Structured catalog facets generated by scripts/normalize-product-catalog.mjs.
ALTER TABLE products ADD COLUMN department TEXT;
ALTER TABLE products ADD COLUMN product_type TEXT;
ALTER TABLE products ADD COLUMN subcategory TEXT;
ALTER TABLE products ADD COLUMN gender TEXT;
ALTER TABLE products ADD COLUMN size_options TEXT;
ALTER TABLE products ADD COLUMN attributes TEXT;

CREATE INDEX IF NOT EXISTS products_department_type_idx
  ON products(department, product_type);

CREATE INDEX IF NOT EXISTS products_brand_idx
  ON products(brand);
